restaurant_project/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:idd>/", views.post_details, name="post_details"),
    path("tag=<slug:tag>/", views.post_by_tag, name="post_by_tag"),
    path("category=<slug:category>/", views.post_by_category, name="post_by_category"),
]

restaurant_project/restaurant_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("meals/", include("meals.urls", namespace="meals")),
    path("reservation/", include("reservation.urls", namespace="reservation")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("about/", include("about.urls", namespace="about")),
    path("contact/", include("contact.urls", namespace="contact")),
    path("", include("home.urls", namespace="home")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Restaurant AdminPanel"
admin.site.site_title = "Restaurant"

restaurant_project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from taggit.managers import TaggableManager
# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self) -> str:
        return self.category_name


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog", blank=True, null=True)
    tags = TaggableManager()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(default=datetime.now())

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"


    def __str__(self) -> str:
        return self.title



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=datetime.now())


    def __str__(self) -> str:
        return self.post.title

restaurant_project/blog/forms.py
from django import forms
from . models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"class":"form-control"})
        }

restaurant_project/blog/views.py
from django.shortcuts import render
from . models import Post, Category, Comment
from taggit.models import Tag
from . forms import CommentForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
# Create your views here.

def post_list(request):
    posts = Post.objects.all()
    search_result = request.GET.get('q')
    if search_result:
        posts = posts.filter(
            Q(title__icontains=search_result)|
            Q(content__icontains=search_result)
        )
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "blog/post_list.html", context={
        "posts": page_obj
    })



def post_details(request, idd: int):
    post = Post.objects.get(pk=idd)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post)
    if request.method == "POST":
        form = CommentForm(request.POST or None)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(reverse("blog:post_details", args=(idd, )))
        else:
            return render(request, "blog/post_details.html", context={
            "post": post,
            "categories": categories,
            "tags": tags,
            "comments": comments,
            "number_of_comments": Comment.objects.filter(post=post).count(),
            "form": form
        })
    return render(request, "blog/post_details.html", context={
        "post": post,
        "categories": categories,
        "tags": tags,
        "comments": comments,
        "number_of_comments": Comment.objects.filter(post=post).count(),
        "form": CommentForm()
    })


def post_by_tag(request, tag):
    posts = Post.objects.filter(tags__name__in=[tag])
    return render(request, "blog/post_list.html", context={
        "posts": posts
    })



def post_by_category(request, category):
    posts = Post.objects.filter(category__category_name=category)
    return render(request, "blog/post_list.html", context={
        "posts": posts
    })

restaurant_project/blog/templates/blog/post_details.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <div class="main-wrap">
        <div class="cover_1 cover_sm">
        <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                <h2 class="heading mb-4">{{ post.title|title }}</h2>

                <div class="post-info">
                    <div class="date-info">{{ post.created }}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">{{ post.category.category_name }}</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">{{ post.author }}</a></div>
                </div>

                </div>
            </div>
            </div>
        </div>
        </div> <!-- .cover_1 -->

    <div class="section">
        <div class="container">
            
            <div class="row">

            <div class="col-md-8">
                <p>{{ post.content|capfirst }}</p>
                
                <div class="tag-widget post-tag-container mb-5 mt-5">
                <div class="tagcloud">
                
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_by_tag' tag.name %}" class="tag-cloud-link">{{ tag.name }}</a>
                    {% endfor %}
                      
                </div>
                </div>


                <div class="pt-5 mt-5">
                    
                    {% if number_of_comments == 1 %}
                        <h3 class="mb-5"> {{ number_of_comments }} comment</h3>
                    {% elif number_of_comments == 0 %}
                        <h3 class="mb-5"> no comment</h3>
                    {% else %}
                        <h3 class="mb-5"> {{ number_of_comments }} comments</h3>
                    {% endif %}
                        
                
                <ul class="comment-list">
                    {% for comment in comments %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'site_static/img/person_1.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.user }}</h3>
                                <div class="meta">{{ comment.created }}</div>
                                <p>{{ comment.content }}</p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <!-- END comment-list -->
                
                <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5">Leave a comment</h3>
                    <form method="POST" class="p-5 bg-light" action="{% url 'blog:post_details' post.id %}">
                        {% csrf_token %}
                        {{ form }}
                         <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Leave A Comment</button>
                    </form>
                </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                    <div class="form-group">
                    <span class="icon fa fa-search"></span>
                    <input type="text" class="form-control" name='q' value="{{ request.Get.q }}" placeholder="Type a keyword and hit enter">
                    </div>
                </form>
                </div>
                <div class="sidebar-box">
                <div class="categories">
                    <h3>Categories</h3>
                    {% for category in categories %}
                            <li><a href="{% url 'blog:post_by_category' category.category_name %}">{{ category.category_name }}</a></li>
                    {% endfor %}
                </div>
                </div>


                <div class="sidebar-box">
                <h3>Tag Cloud</h3>
                <div class="tagcloud">
                
                    {% for tag in tags %}
                        <a href="{% url 'blog:post_by_tag' tag.name %}" class="tag-cloud-link">{{ tag.name }}</a>
                    {% endfor %}

                </div>
                </div>


            </div>

            </div>

            
        </div>
        </div> <!-- .section -->
    


    </div> <!-- .main-wrap -->
{% endblock body %}

restaurant_project/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <div class="main-wrap">
        <div class="cover_1 cover_sm">
        <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                <h2 class="heading">Blog Grid</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                </div>
            </div>
            </div>
        </div>
        </div> <!-- .cover_1 -->

    <div class="section">
        <div class="container">
            
            <div class="row mb-5">

                {% for post in posts %}
                    <div class="col-md-4">
                        <div class="media d-block media-bg-white mb-5" data-aos="fade-up"  data-aos-delay="400">
                            <figure>
                                <a href="{% url 'blog:post_details' post.id %}"><img src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid"></a>
                            </figure>
                            <div class="media-body">
                                <h3><a href="{% url 'blog:post_details' post.id %}">{{ post.title|title }}</a></h3>
                                <p class="post-meta"><span><span class="fa fa-calendar"></span>{{ post.created }}</span></p>
                                <p class="mb-4">{{ post.content|capfirst }}</p>
                                <p><a href="{% url 'blog:post_details' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                            </div>
                        </div> <!-- .media -->
                    </div>
                {% endfor %}
                
            </div>

            <div class="row">
              
                {% if posts.has_other_pages %}
  
                  <div class="col-md-12">
                    <ul class="pagination custom-pagination">
                      {% if posts.has_previous %}
                        <li class="page-item prev"><a class="page-link" href="?page={{posts.previous_page_number}}"><i class="fa fa-angle-left"></i></a></li>
                      {% else %}
                        <li class="disabled"></li>
                      {% endif %}
  
                      {% for pages in posts.paginator.page_range %}
                        {% if posts.number == pages %}
                          <li class="page-item active"><a class="page-linkx href="#">{{pages}}</a></li>
                        {% else %}
                          <li class="page-item active"><a class="page-linkx" href="?page={{pages}}">{{pages}}</a></li>
                        {% endif %}
                        
                      {% endfor %}
                      
  
                      {% if posts.has_next %}
                        <li class="page-item next"><a class="page-link" href="?page={{posts.next_page_number}}"><i class="fa fa-angle-right"></i></a></li>
                      {% else %}
                        <li class="disabled"></li>
                      {% endif %} 
                    </ul>
  
  
                  </div>
                {% endif %}
              </div>
        </div> <!-- .section -->
    


    </div> <!-- .main-wrap -->
{% endblock body %}
    