restaurant_project/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:idd>/", views.post_details, name="post_details"),
    path("tag=<slug:tag>/", views.post_by_tag, name="post_by_tag"),
    path("category=<slug:category>/", views.post_by_category, name="post_by_category"),
]

restaurant_project/reservation/urls.py
from . import views
from django.urls import path


app_name = "reservation"


urlpatterns = [
    path("", views.reserve_table, name="reserve_table")
]

restaurant_project/restaurant_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("meals/", include("meals.urls", namespace="meals")),
    path("reservation/", include("reservation.urls", namespace="reservation")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("about/", include("about.urls", namespace="about")),
    path("contact/", include("contact.urls", namespace="contact")),
    path("", include("home.urls", namespace="home")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Restaurant AdminPanel"
admin.site.site_title = "Restaurant"

restaurant_project/reservation/models.py
from django.db import models

# Create your models here.

class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    number_of_person = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()

    
    def __str__(self) -> str:
        return self.name

restaurant_project/reservation/forms.py
from django import forms
from .models import Reservation



class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control"
                }),

            "email": forms.EmailInput(attrs={
                "class": "form-control"
                }),
            "phone": forms.NumberInput(attrs={
                "class": "form-control"
                }),
            "number_of_person": forms.NumberInput(attrs={
                "class": "form-control"
                }),

            "date": forms.DateInput(attrs={
                "class": "form-control"
                }),

            "time": forms.TimeInput(attrs={
                "class": "form-control"
                }),
        }

restaurant_project/reservation/views.py
from django.shortcuts import render
from .forms import ReservationForm
# Create your views here.

def reserve_table(request):
    if request.method == "POST":
        form = ReservationForm(request.POST or None)
        if form.is_valid():
            form.save()
        else:
            return render(request, "reservation/reservation.html", context={
                "form": form
            })
    return render(request, "reservation/reservation.html", context={
        "form": ReservationForm()
    })

restaurant_project/reservation/templates/reservation/reservation.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  

  
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Reservation</h2>
                  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
        
        <div class="section" data-aos="fade-up">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Reservation</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="col-md-10 p-5 form-wrap">
                
                <form action="{% url 'reservation:reserve_table' %}" method="POST">
                  {% csrf_token %}
                  {{ form }}
                  <input type="submit" class="btn btn-primary" value="submit" style="margin-top: 20px;">  
                </form>


              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="map-wrap" id="map"  data-aos="fade"></div>

        <div class="section" data-aos="fade">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Customer's Reviews</h2>
              </div>
            </div>
            <div class="row justify-content-center text-center" data-aos="fade-up">
              <div class="col-md-8">
                <div class="owl-carousel home-slider-loop-false">

                
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quaerat recusandae molestias incidunt sapiente sit numquam delectus mollitia! Non laudantium impedit voluptas consequatur corrupti. Cumque consequuntur nemo eos et error!&rdquo;</p>
                      <div class="author">
                        <img src="{% static 'site_static/img/person_1.jpg' %}" alt="Image placeholder" class="mb-3">
                        <h4>Maxim Smith</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Sint adipisci laborum dolorum ipsa quidem alias ipsum aperiam aut! Quis rerum soluta dolorem iure nihil velit error sequi? Dignissimos accusantium adipisci unde officia? Dolores aut sequi dolorum repellendus quod.&rdquo;</p>
                      <div class="author">
                        <img src="{% static 'site_static/img/person_2.jpg' %}" alt="Image placeholder" class="mb-3">
                        <h4>Geert Green</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ratione alias iure ab facere quia aliquam dolor et voluptates esse nihil corporis distinctio hic ea quo ducimus autem cum amet. Quos accusamus iusto porro nulla temporibus numquam commodi soluta.&rdquo;</p>
                      <div class="author">
                        <img src="{% static 'site_static/img/person_3.jpg' %}" alt="Image placeholder" class="mb-3">
                        <h4>Dennis Roman</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ad quod aspernatur ipsa. Numquam expedita delectus qui ad explicabo voluptas eos vel reiciendis magnam rerum quaerat quisquam accusantium quae saepe ipsam ullam ut ea molestiae porro. Recusandae veniam maxime.&rdquo;</p>
                      <div class="author">
                        <img src="{% static 'site_static/img/person_2.jpg' %}" alt="Image placeholder" class="mb-3">
                        <h4>Geert Green</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                </div>
              </div>
            </div>
          </div>  
        </div> <!-- .section -->

  

      </div> <!-- .main-wrap -->
      
{% endblock body %}